import json
from pathlib import Path

from mini_akinator.models import Character

DATA_DIR = Path("data/characters")


CHARACTERS: list[dict[str, str | bool]] = [
    {
        "name": "Harry Potter",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": False,
        "gender": "male",
        "house": "gryffindor",
        "blood_status": "half-blood",
        "role": "student",
        "species": "human",
        "alive": True,
        "loyal_to_order": True,
        "death_eater": False,
        "has_wand": True,
        "wears_glasses": True,
        "hair_color": "black",
    },
    {
        "name": "Hermione Granger",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": False,
        "gender": "female",
        "house": "gryffindor",
        "blood_status": "muggle-born",
        "role": "student",
        "species": "human",
        "alive": True,
        "loyal_to_order": True,
        "death_eater": False,
        "has_wand": True,
        "wears_glasses": False,
        "hair_color": "brown",
    },
    {
        "name": "Ron Weasley",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": False,
        "gender": "male",
        "house": "gryffindor",
        "blood_status": "pure-blood",
        "role": "student",
        "species": "human",
        "alive": True,
        "loyal_to_order": True,
        "death_eater": False,
        "has_wand": True,
        "wears_glasses": False,
        "hair_color": "red",
    },
    {
        "name": "Albus Dumbledore",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": False,
        "gender": "male",
        "house": "gryffindor",
        "blood_status": "half-blood",
        "role": "headmaster",
        "species": "human",
        "alive": False,
        "loyal_to_order": True,
        "death_eater": False,
        "has_wand": True,
        "wears_glasses": False,
        "hair_color": "white",
    },
    {
        "name": "Severus Snape",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": True,
        "gender": "male",
        "house": "slytherin",
        "blood_status": "half-blood",
        "role": "teacher",
        "species": "human",
        "alive": False,
        "loyal_to_order": True,
        "death_eater": True,
        "has_wand": True,
        "wears_glasses": False,
        "hair_color": "black",
    },
    {
        "name": "Draco Malfoy",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": True,
        "gender": "male",
        "house": "slytherin",
        "blood_status": "pure-blood",
        "role": "student",
        "species": "human",
        "alive": True,
        "loyal_to_order": False,
        "death_eater": False,
        "has_wand": True,
        "wears_glasses": False,
        "hair_color": "blond",
    },
    {
        "name": "Lord Voldemort",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": True,
        "gender": "male",
        "house": "slytherin",
        "blood_status": "half-blood",
        "role": "other",
        "species": "human",
        "alive": False,
        "loyal_to_order": False,
        "death_eater": False,
        "has_wand": True,
        "wears_glasses": False,
        "hair_color": "other",
    },
    {
        "name": "Rubeus Hagrid",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": False,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": False,
        "gender": "male",
        "house": "none",
        "blood_status": "unknown",
        "role": "teacher",
        "species": "half-giant",
        "alive": True,
        "loyal_to_order": True,
        "death_eater": False,
        "has_wand": False,
        "wears_glasses": False,
        "hair_color": "black",
    },
    {
        "name": "Minerva McGonagall",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": False,
        "gender": "female",
        "house": "gryffindor",
        "blood_status": "half-blood",
        "role": "teacher",
        "species": "human",
        "alive": True,
        "loyal_to_order": True,
        "death_eater": False,
        "has_wand": True,
        "wears_glasses": True,
        "hair_color": "other",
    },
    {
        "name": "Luna Lovegood",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": False,
        "gender": "female",
        "house": "ravenclaw",
        "blood_status": "pure-blood",
        "role": "student",
        "species": "human",
        "alive": True,
        "loyal_to_order": True,
        "death_eater": False,
        "has_wand": True,
        "wears_glasses": False,
        "hair_color": "blond",
    },
    {
        "name": "Neville Longbottom",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": False,
        "gender": "male",
        "house": "gryffindor",
        "blood_status": "pure-blood",
        "role": "student",
        "species": "human",
        "alive": True,
        "loyal_to_order": True,
        "death_eater": False,
        "has_wand": True,
        "wears_glasses": False,
        "hair_color": "brown",
    },
    {
        "name": "Bellatrix Lestrange",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": True,
        "gender": "female",
        "house": "slytherin",
        "blood_status": "pure-blood",
        "role": "other",
        "species": "human",
        "alive": False,
        "loyal_to_order": False,
        "death_eater": True,
        "has_wand": True,
        "wears_glasses": False,
        "hair_color": "black",
    },
    {
        "name": "Sirius Black",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": False,
        "gender": "male",
        "house": "gryffindor",
        "blood_status": "pure-blood",
        "role": "other",
        "species": "human",
        "alive": False,
        "loyal_to_order": True,
        "death_eater": False,
        "has_wand": True,
        "wears_glasses": False,
        "hair_color": "black",
    },
    {
        "name": "Dobby",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": False,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": False,
        "gender": "other",
        "house": "none",
        "blood_status": "unknown",
        "role": "other",
        "species": "elf",
        "alive": False,
        "loyal_to_order": True,
        "death_eater": False,
        "has_wand": False,
        "wears_glasses": False,
        "hair_color": "other",
    },
    {
        "name": "Lucius Malfoy",
        "universe": "Harry Potter",
        "is_fictional": True,
        "is_human": True,
        "has_powers": True,
        "wears_mask": False,
        "is_villain": True,
        "gender": "male",
        "house": "slytherin",
        "blood_status": "pure-blood",
        "role": "other",
        "species": "human",
        "alive": True,
        "loyal_to_order": False,
        "death_eater": True,
        "has_wand": True,
        "wears_glasses": False,
        "hair_color": "blond",
    },
]


def slugify(name: str) -> str:
    return name.lower().replace(" ", "_").replace("-", "_")


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    for payload in CHARACTERS:
        character = Character.model_validate(payload)
        path = DATA_DIR / f"{slugify(character.name)}.json"
        path.write_text(
            json.dumps(character.model_dump(), ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )

    print(f"Wrote {len(CHARACTERS)} characters to {DATA_DIR}")


if __name__ == "__main__":
    main()
